export default function Head() {
  return (
    <>
      <title>From Retail to Tech</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href='/Square_TransparentLines_Mushroom copy.png'
      />
    </>
  )
}
